
server:
  port: ${SERVER_PORT:8088}

share-folder:
  path: ${SHARE_FOLDER_DIRECTORY:/share}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://database:8890/sparql}
  defaultGraphUri: ${TARGET_GRAPH:http://mu.semte.ch/application}
  defaultBatchSize: ${BATCH_SIZE:100}
  defaultLimitSize: ${LIMIT_SIZE:100}
  maxRetry: ${MAX_RETRY:5}
  
spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
